--- 
abstract: Steve Gibson's Perfect Paper Passwords
author: 
  - Andy Armstrong  C<< <andy@hexten.net> >>
build_requires: 
  Test::Deep: 0.096
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Crypt-PerfectPaperPasswords
no_index: 
  directory: 
    - inc
    - t
requires: 
  Crypt::Rijndael: 0
  Digest::SHA256: 0
  Getopt::Long: 0
  Scalar::Util: 0
  Time::HiRes: 0
  perl: 5.8.0
version: 0.05
